# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b7d2ce625793ab3d2a96849ea458dcce572ead9af5db4048ca48471c7d2a5407aa0dbb21a93554f484379866c90a19e3c841bc6841dd50a1685de024c9dcd1a

test:
  secret_key_base: 4c266d1f38321002ca0885c1778fed21a7a79a07447d0acfe53493b4b79a100c72b7ebc64a604be008d42f426d6ecf58eb00f86b31b81c72b6eae9b6501a199a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
